# Generated by Django 4.2.4 on 2023-09-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_login_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
