# Generated by Django 4.2.4 on 2023-09-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_login_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
