# Generated by Django 4.2.4 on 2023-09-02 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_mail', models.CharField(max_length=100, verbose_name='from')),
                ('to_mail', models.EmailField(max_length=100, verbose_name='to')),
                ('subject', models.TextField()),
                ('message', models.TextField()),
            ],
        ),
    ]
